if (WIN32)
  file( TO_CMAKE_PATH "$ENV{DP_3RDPARTY_PATH}/OpenEXR/" OPENEXRROOT)
  if ( EXISTS "${OPENEXRROOT}" )
    set( ENV{OPENEXRROOT} "${OPENEXRROOT}" )
    set( OPENEXR_BINDIR "$ENV{OPENEXRROOT}/win32-${DP_ARCH}/bin" )
    set( OPENEXR_LIBDIR "$ENV{OPENEXRROOT}/win32-${DP_ARCH}/lib" )
    set( OPENEXR_INCLUDE_DIRS "$ENV{OPENEXRROOT}/include" )
  endif()
elseif(UNIX)
  include(FindPkgConfig)
  pkg_check_modules(OPENEXR OpenEXR REQUIRED)
endif()

